# Generated by Django 4.1.1 on 2024-04-28 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptage', '0006_personne'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_depart', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='membres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=32)),
                ('prenom', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profession', models.CharField(max_length=32)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptage.departement')),
            ],
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
    ]
