# Generated by Django 4.1.1 on 2024-04-28 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptage', '0007_departement_membres_delete_personne'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='membre',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='cryptage.membres'),
            preserve_default=False,
        ),
    ]
