# Generated by Django 4.1.1 on 2024-04-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptage', '0008_stock_membre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-date_generation']},
        ),
    ]
