# Generated by Django 6.0.1 on 2026-01-31 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptage', '0009_alter_stock_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64, unique=True)),
                ('template_recto', models.ImageField(upload_to='card_templates/')),
                ('template_verso', models.ImageField(upload_to='card_templates/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template de Carte',
                'verbose_name_plural': 'Templates de Cartes',
            },
        ),
        migrations.RemoveField(
            model_name='stock',
            name='image',
        ),
        migrations.AddField(
            model_name='membres',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='membres/photos/'),
        ),
        migrations.AddField(
            model_name='stock',
            name='carte_pdf',
            field=models.FileField(blank=True, null=True, upload_to='cartes/pdf/'),
        ),
        migrations.AddField(
            model_name='stock',
            name='carte_recto',
            field=models.ImageField(blank=True, null=True, upload_to='cartes/recto/'),
        ),
        migrations.AddField(
            model_name='stock',
            name='carte_verso',
            field=models.ImageField(blank=True, null=True, upload_to='cartes/verso/'),
        ),
        migrations.AddField(
            model_name='stock',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='stock',
            name='template_utilise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cryptage.cardtemplate'),
        ),
    ]
